name: Demo Deployment
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Running build"
  test:
    runs-on: ubantu-latest
    steps:
      - name: Test Phase
        run: echo "Running Test cases"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        run: echo "Deploying app"
            
